# .pre-commit-config.yaml
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 91ab4bf57e58b32adf1a122681f6ebe164d081c8 # v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []  # optionally list allowed types: [feat, fix, chore, ...]
